
name: Complex Workflows

on: push

jobs:

  ubuntu:
    - runs-on: ubuntu-latest
      steps:
        - run: date
  windows:
    - runs-on: windows-latest
      steps:
        - run: date
  macos:
    - runs-on: macos-latest
      steps:
        - run: date
  dependancies:
      need: [ubuntu, windows, macos]
    - runs-on: macos-latest
      steps:
        - run:date

